import type { Metadata } from "next";
import "./globals.css";
import AppInitializer from "../store/AppInitializer";

import RootStyleRegistry from "../emotion/emotion-root-style-registry";
import { getData } from "../utils/apiMock";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = cookies();
  const userType = cookiesStore.get('user-type')
  const data = await getData(userType?.value as string);
  console.log('layout page for zustanf in client', data);

  return (
    <html lang="en">
      <body >
        <RootStyleRegistry>
          <AppInitializer user={data}>{children}</AppInitializer>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
